csv_path: ./data/complete-mammo.csv
dl_workers:
  train: 8
  val: 4
eval_interval: 5
freeze_text_model: true
freeze_vision_model: true
max_checkpoints: 5
pretrained_model_cfg:
  num_views: 4
  text_model_name_or_path: microsoft/BiomedVLP-CXR-BERT-general
  verbose: false
  vision_model_name_or_path: microsoft/rad-dino
project_dir: ./mammoclip-v1
save_interval: 5
seed: 42
train_ds:
  attrs_:
    alt_text_cols:
    - aug_report
    alt_text_prob: 0.5
    cache_dir: .cache
    image_cols:
    - r_cc
    - l_cc
    - r_mlo
    - l_mlo
    image_preprocessor:
      attrs_:
        extract_largest_cc: true
        output_size: &id001 !!python/tuple
        - 518
        - 518
        use_clahe: true
      class_: MammogramPreprocessor
    path_to_df: ./mammoclip-v1/train.csv
    pid_col: id
    text_col: report
    tokenizer: microsoft/BiomedVLP-CXR-BERT-general
    tokenizer_kwargs:
      max_length: 256
      padding: max_length
      return_tensors: pt
      truncation: true
    transform_function:
      attrs_:
        degrees: 10
        is_validation: false
        mean: &id002 !!python/tuple
        - 0.281
        noise_std: &id003 !!python/tuple
        - 0.0
        - 0.03
        scale: &id004 !!python/tuple
        - 0.9
        - 1.1
        shear: !!python/tuple
        - 10
        - 10
        size: *id001
        std: &id005 !!python/tuple
        - 0.217
        translate: &id006 !!python/tuple
        - 0.05
        - 0.05
      class_: MammogramTransform
    weights_col: weight
  class_: MammogramDataset
training_params:
  batch_size: 32
  gradient_accumulation_steps: 1
  lr_max: 0.0001
  lr_min: 5.0e-07
  lr_scheduler: wsd_schedule
  max_grad_norm: 1.0
  mixed_precision: bf16
  num_epochs: 100
  steady_fraction: 0.25
  train_fraction: 0.8
  warmup_fraction: 0.05
  weight_decay: 1.0e-06
val_ds:
  attrs_:
    alt_text_prob: 0.0
    cache_dir: .cache
    image_cols:
    - r_cc
    - l_cc
    - r_mlo
    - l_mlo
    image_preprocessor:
      attrs_:
        extract_largest_cc: true
        output_size: *id001
        use_clahe: true
      class_: MammogramPreprocessor
    path_to_df: ./mammoclip-v1/val.csv
    pid_col: id
    text_col: report
    tokenizer: microsoft/BiomedVLP-CXR-BERT-general
    tokenizer_kwargs:
      max_length: 256
      padding: max_length
      return_tensors: pt
      truncation: true
    transform_function:
      attrs_:
        degrees: 10
        is_validation: true
        mean: *id002
        noise_std: *id003
        scale: *id004
        shear: !!python/tuple
        - 20
        - 20
        size: *id001
        std: *id005
        translate: *id006
      class_: MammogramTransform
  class_: MammogramDataset
