project_dir: ./mammoclip-v4
seed: 42
csv_path: ./data/essential-mammo.csv
freeze_vision_model: false
freeze_text_model: true
ddp_kwargs:
  find_unused_parameters: true
training_params:
  num_epochs: 50
  train_fraction: 0.8
  batch_size: 8
  lr_max: 5.0e-05
  lr_min: 5.0e-07
  vision_lr_mul: 1.0
  text_lr_mul: 1.0
  fusion_lr_mul: 5.0
  lr_scheduler: wsd_schedule
  warmup_fraction: 0.05
  steady_fraction: 0.25
  gradient_accumulation_steps: 4
  max_grad_norm: 1.0
  weight_decay: 0.01
  eps: 1.0e-08
  betas:
    - 0.9
    - 0.98
  mixed_precision: bf16
dl_workers:
  train: 2
  val: 2
train_ds:
  class_: MammogramDataset
  attrs_:
    alt_text_cols:
      - aug_report
      - aug_report02
    alt_text_prob: 0.66
    cache_dir: .cache
    image_cols:
      - r_cc
      - l_cc
      - r_mlo
      - l_mlo
    image_preprocessor:
      attrs_:
        extract_largest_cc: true
        output_size:
          - 518
          - 518
        use_clahe: true
      class_: MammogramPreprocessor
    path_to_df: ./mammoclip-v4/train.csv
    pid_col: id
    text_col: report
    tokenizer: microsoft/BiomedVLP-CXR-BERT-general
    tokenizer_kwargs:
      max_length: 256
      padding: max_length
      return_tensors: pt
      truncation: true
    transform_function:
      attrs_:
        brightness: 0.15
        contrast: 0.15
        degrees: 10
        dropout_prob: 0.15
        gamma:
          - 1.0
          - 1.0
        is_validation: false
        mean:
          - 0.281
        noise_std:
          - 0.0
          - 0.05
        prob: 0.5
        remove_range:
          - 0.15
          - 0.35
        scale:
          - 0.8
          - 1.2
        shear:
          - -10
          - 10
          - -10
          - 10
        size:
          - 518
          - 518
        std:
          - 0.217
        translate:
          - 0.05
          - 0.05
      class_: MammogramTransform
    weights_col: weight
val_ds:
  class_: MammogramDataset
  attrs_:
    alt_text_prob: 0.0
    cache_dir: .cache
    image_cols:
      - r_cc
      - l_cc
      - r_mlo
      - l_mlo
    image_preprocessor:
      attrs_:
        extract_largest_cc: true
        output_size:
          - 518
          - 518
        use_clahe: true
      class_: MammogramPreprocessor
    path_to_df: ./mammoclip-v4/val.csv
    pid_col: id
    text_col: report
    tokenizer: microsoft/BiomedVLP-CXR-BERT-general
    tokenizer_kwargs:
      max_length: 256
      padding: max_length
      return_tensors: pt
      truncation: true
    transform_function:
      attrs_:
        is_validation: true
        mean:
          - 0.281
        size:
          - 518
          - 518
        std:
          - 0.217
      class_: MammogramTransform
    weights_col: weight
infer_settings:
  csv_path: ./data/inference-clean.csv
  sample_size: 1000
  replace: true
  weight_col: weight
  view_cols:
    - r_cc
    - l_cc
    - r_mlo
    - l_mlo
  batch_size: 16
  tau: 100.0
  query_dict:
    birads:
      label_col: birads
      query2label:
        BI-RADS 0: 0
        BI-RADS 1: 1
        BI-RADS 2: 2
        BI-RADS 3: 3
        BI-RADS 4: 4
        BI-RADS 5: 5
        BI-RADS 6: 6
    calcification:
      label_col: any_microcal
      query2label:
        Microcalcification present: 1
        No microcalcification: 0
    composition:
      label_col: composition
      query2label:
        Composition A: 0
        Composition B: 1
        Composition C: 2
        Composition D: 3
    mass:
      label_col: any_mass
      query2label:
        Mass present: 1
        No mass: 0
  tensorboard_metrics:
    - auc
    - accuracy
  logger_metrics:
    - report
    - auc
eval_interval: 1
infer_interval: 1
save_interval: 1
metric_criterion: highest
metric: accuracy
metric_query: birads
max_checkpoints: 4
pretrained_model_cfg:
  vision_model_name_or_path: microsoft/rad-dino
  text_model_name_or_path: microsoft/BiomedVLP-CXR-BERT-general
  num_views: 4
  fusion_type: linear
  verbose: false
