csv_path: ./data/essential-mammo.csv
dl_workers:
  train: 2
  val: 2
eval_interval: 1
freeze_text_model: true
freeze_vision_model: false
ddp_kwargs:
  find_unused_parameters: true
max_checkpoints: 4
pretrained_model_cfg:
  fusion_type: linear
  num_views: 4
  text_model_name_or_path: microsoft/BiomedVLP-CXR-BERT-general
  verbose: false
  vision_model_name_or_path: microsoft/rad-dino
project_dir: ./mammoclip-v2
save_interval: 1
seed: 42
train_ds:
  attrs_:
    alt_text_cols:
      - aug_report
      - aug_report02
    alt_text_prob: 0.66
    cache_dir: .cache
    image_cols:
      - r_cc
      - l_cc
      - r_mlo
      - l_mlo
    image_preprocessor:
      attrs_:
        extract_largest_cc: true
        output_size:
          - 518
          - 518
        use_clahe: true
      class_: MammogramPreprocessor
    path_to_df: ./mammoclip-v2/train.csv
    pid_col: id
    text_col: report
    tokenizer: microsoft/BiomedVLP-CXR-BERT-general
    tokenizer_kwargs:
      max_length: 256
      padding: max_length
      return_tensors: pt
      truncation: true
    transform_function:
      attrs_:
        degrees: 15
        is_validation: false
        mean:
          - 0.281
        noise_std:
          - 0.0
          - 0.02
        scale:
          - 0.8
          - 1.2
        shear:
          - -10
          - 10
          - -10
          - 10
        size:
          - 518
          - 518
        std:
          - 0.217
        translate:
          - 0.05
          - 0.05
      class_: MammogramTransform
    weights_col: weight
  class_: MammogramDataset
training_params:
  batch_size: 8
  gradient_accumulation_steps: 4
  lr_max: 5.0e-5
  lr_min: 5.0e-07
  vision_lr_mul: 1.0
  text_lr_mul: 1.0
  fusion_lr_mul: 5.0
  lr_scheduler: wsd_schedule
  max_grad_norm: 1.0
  mixed_precision: bf16
  num_epochs: 30
  steady_fraction: 0.05
  train_fraction: 0.8
  warmup_fraction: 0.05
  weight_decay: 0.05
  betas:
    - 0.9
    - 0.98
  eps: 1.0e-08
val_ds:
  attrs_:
    alt_text_prob: 0.0
    weights_col: weight
    cache_dir: .cache
    image_cols:
      - r_cc
      - l_cc
      - r_mlo
      - l_mlo
    image_preprocessor:
      attrs_:
        extract_largest_cc: true
        output_size:
          - 518
          - 518
        use_clahe: true
      class_: MammogramPreprocessor
    path_to_df: ./mammoclip-v1/val.csv
    pid_col: id
    text_col: report
    tokenizer: microsoft/BiomedVLP-CXR-BERT-general
    tokenizer_kwargs:
      max_length: 256
      padding: max_length
      return_tensors: pt
      truncation: true
    transform_function:
      attrs_:
        degrees: 0
        is_validation: true
        mean:
          - 0.281
        noise_std:
          - 0.0
          - 0.0
        scale:
          - 1.0
          - 1.0
        shear:
          - 0
          - 0
          - 0
          - 0
        size:
          - 518
          - 518
        std:
          - 0.217
        translate:
          - 0.0
          - 0.0
      class_: MammogramTransform
  class_: MammogramDataset
